version: '2'

services:
    api:
        build: .
        environment:
         - API_PORT=${API_PORT}
        volumes:
         - ${VOLUME_MODELS}:/src/api/api/models
         - ${VOLUME_DIST}:/src/api/api/dist
         - ${VOLUME_MIDDLEWARE}:/src/api/api/middleware/index.js
        depends_on:
         - mongo
        ports:
         - "${API_PORT}:3000"
        links:
         - mongo:mongo
        restart: always

    mongo:
        image: mongo:latest
        volumes:
         - ./db_data:/data/db
        restart: always

    mongo-ui:
        image: mongo-express:latest
        depends_on:
         - mongo
        links:
         - mongo:mongo
        ports:
         - "${ADMIN_PORT}:8081"
        restart: always